#!/usr/bin/env bash

export SHELL="/bin/bash"
export acmeshell="/bin/bash"
export BROWSER=firefox
export tabstop=8
export TERM=dumb
export PAGER=nobs

fontsrv &
plumber

acme -a -f "/mnt/font/LucidaMonoEF-Roman/12a/font" $1
