#!/usr/bin/env bash

export SHELL="/bin/bash"
export acmeshell="/bin/bash"
export BROWSER=firefox
export tabstop=2
export TERM=dumb
export PAGER=nobs

plumber

acme -a -f /mnt/font/'Hack Regular'/11a/font $1
